name: Perform Unit Test

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
    - name: Install Mamba
      run: |
        conda env update --file .github/workflows/environment.yml --name base mamba
    - name: Install Dependencies with Mamba
      run: |
        mamba env update -n base --file .github/workflows/environment.yml
    - name: Test with pytest
      run: |
        conda install pytest
        pytest
